FROM node:22-alpine3.24
RUN rm -rf /usr/local/lib/node_modules/npm /usr/local/lib/node_modules/corepack \
 && rm -f  /usr/local/bin/npm /usr/local/bin/npx /usr/local/bin/corepack
RUN addgroup -S -g 65532 app \
 && adduser  -S -u 65532 -G app -h /app -s /sbin/nologin app \
 && mkdir -p /app && chown app:app /app
WORKDIR /app
USER app
EXPOSE 3000
ENTRYPOINT []
CMD []
