FROM python:3.14-alpine3.24
RUN rm -rf /usr/local/lib/python3.14/site-packages/pip \
          /usr/local/lib/python3.14/site-packages/pip-*.dist-info \
          /usr/local/lib/python3.14/ensurepip \
 && rm -f  /usr/local/bin/pip /usr/local/bin/pip3 /usr/local/bin/pip3.14
RUN addgroup -S -g 65532 app \
 && adduser  -S -u 65532 -G app -h /app -s /sbin/nologin app \
 && mkdir -p /app && chown app:app /app
WORKDIR /app
USER app
ENTRYPOINT []
CMD []
