FROM golang:1.26-alpine3.24
RUN addgroup -S -g 65532 app \
 && adduser  -S -u 65532 -G app -h /app -s /sbin/nologin app \
 && mkdir -p /app/go /app/.cache/go && chown -R app:app /app
ENV GOPATH=/app/go GOCACHE=/app/.cache/go GOMODCACHE=/app/go/pkg/mod GOFLAGS=-buildvcs=false
WORKDIR /app
USER app
ENTRYPOINT []
CMD []
