FROM amazoncorretto:21.0.12-alpine
RUN addgroup -S -g 65532 app \
 && adduser  -S -u 65532 -G app -h /app -s /sbin/nologin app \
 && mkdir -p /app && chown app:app /app
WORKDIR /app
USER app
EXPOSE 9966
ENTRYPOINT []
CMD []
